name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  lint:
    name: deno lint

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Run linter
        run: deno lint --unstable

  test:
    name: Deno Stable

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Run tests
        run: deno test --allow-all --unstable

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "lts"

      - name: Create latest changelog
        run: npx conventional-changelog-cli -u false -o latest-changelog.md -u false

      - name: Create a Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: "./latest-changelog.md"
